vim.api.nvim_set_keymap('n', '<leader>d', ':NERDTreeToggle | :silent NERDTreeMirror<cr>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>v', ':vs<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>f', ':GFiles<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>a', ':Ack!<space>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>A', ':Ack!<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-h>', '<C-w>h', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-j>', '<C-w>j', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-k>', '<C-w>k', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-l>', '<C-w>l', {noremap = true})
